name: Deploy latest course version

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - run: cd $GITHUB_WORKSPACE
    
    # Install SSH Key to authorize operations on the repo
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.0.2
      with:
        key: ${{ secrets.ACTION_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    # Configure Git for commits on gh-pages
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: npm install

    # Runs a set of commands using the runners shell
    - name: Deploy course
      id: deploy
      run: npm run deploy && echo ::set-output name=status::success
      
    - name: Check on failures
      if: steps.deploy.outputs.status != 'success'
      run: exit 1
