name: Deploy latest course version

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 18.x

    # Checks-out the repository under $GITHUB_WORKSPACE
    - name: Checkout repo
      uses: actions/checkout@v3.5.2

    # Install SSH Key to authorize operations by the Runner on the repo
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.5.1
      with:
        key: ${{ secrets.ACTION_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # Configure Git for commits on gh-pages
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Install dependencies
      run: npm install

    - name: Deploy course
      id: deploy
      run: npx courses-md --version npm run deploy
